const ActionTypes = {
    GET_MENUTYPES: 'GET_MENUTYPES',
    GET_USERINFO: 'GET_USERINFO',
    GET_SENSORTYPES: 'GET_SENSORTYPES',
    GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
    CHANGE_VALUENOTIFICATION: 'CHANGE_VALUENOTIFICATION',
    EDIT_NOTIFICATIONDATA: 'EDIT_NOTIFICATIONDATA',
    SAVE_CHANGESEDITUSER: 'SAVE_CHANGESEDITUSER',
    GET_MYACCOUNT: 'GET_MYACCOUNT',
    EDIT_MYACCOUNTDATA: 'EDIT_MYACCOUNTDATA',
    SAVE_CHANGESEDITMYACCOUNT: 'SAVE_CHANGESEDITMYACCOUNT',
    GET_PARAMETERSRANGE: 'GET_PARAMETERSRANGE',
    SET_PARAMETERSRANGE: 'SET_PARAMETERSRANGE',
    GET_MEDIDORESINFO: 'GET_MEDIDORESINFO'
  };

  export default ActionTypes;
